[pytest]
asyncio_mode = auto
addopts = --reruns 2 --reruns-delay 1
testpaths = app/tests
python_files = test_*.py
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning
env =
    ENVIRONMENT=test
    TESTING=true
    POSTMARK_SERVER_TOKEN=
    SMTP_HOST=
    EMAILS_FROM_EMAIL=
