"""rename flutterwave fields to paystack

Revision ID: 070ca04fb75a
Revises: dc33e2a31bde
Create Date: 2026-04-22 17:57:14.646407

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '070ca04fb75a'
down_revision = 'dc33e2a31bde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Update Payment table
    op.add_column('payment', sa.Column('paystack_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    try:
        op.drop_index('ix_payment_flutterwave_id', table_name='payment')
    except Exception:
        pass
    op.create_index(op.f('ix_payment_paystack_id'), 'payment', ['paystack_id'], unique=False)
    op.drop_column('payment', 'flutterwave_id')

    # Update System Settings table
    op.add_column('system_settings', sa.Column('paystack_public_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('system_settings', sa.Column('paystack_secret_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    
    op.alter_column('system_settings', 'bank_name',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(length=255),
               existing_nullable=True)
    op.alter_column('system_settings', 'account_number',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(length=50),
               existing_nullable=True)
    op.alter_column('system_settings', 'account_name',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(length=255),
               existing_nullable=True)
               
    op.drop_column('system_settings', 'flutterwave_public_key')
    op.drop_column('system_settings', 'flutterwave_secret_key')

    # Add missing index for user created_at if it doesn't exist
    try:
        op.create_index(op.f('ix_user_created_at'), 'user', ['created_at'], unique=False)
    except Exception:
        pass
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_index(op.f('ix_user_created_at'), table_name='user')
    except Exception:
        pass
    
    op.add_column('system_settings', sa.Column('flutterwave_secret_key', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('system_settings', sa.Column('flutterwave_public_key', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    
    op.alter_column('system_settings', 'account_name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('system_settings', 'account_number',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('system_settings', 'bank_name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
               
    op.drop_column('system_settings', 'paystack_secret_key')
    op.drop_column('system_settings', 'paystack_public_key')
    
    op.add_column('payment', sa.Column('flutterwave_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_payment_paystack_id'), table_name='payment')
    op.create_index('ix_payment_flutterwave_id', 'payment', ['flutterwave_id'], unique=False)
    op.drop_column('payment', 'paystack_id')
    # ### end Alembic commands ###
