"""add_organization_id_to_workspace

Revision ID: 15ace1d067b7
Revises: 0cd2235c8e5f
Create Date: 2026-01-16 01:58:48.169122

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '15ace1d067b7'
down_revision = '0cd2235c8e5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspace', sa.Column('organization_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_workspace_organization_id'), 'workspace', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'workspace', 'organization', ['organization_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspace', type_='foreignkey')
    op.drop_index(op.f('ix_workspace_organization_id'), table_name='workspace')
    op.drop_column('workspace', 'organization_id')
    # ### end Alembic commands ###
