"""update_payment_schema

Revision ID: 1eff9d79e209
Revises: ab55fad7e951
Create Date: 2026-04-03 07:58:54.637173

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1eff9d79e209'
down_revision = 'ab55fad7e951'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False))
    op.add_column('payment', sa.Column('payment_method', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('payment', sa.Column('flutterwave_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('payment', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_payment_flutterwave_id'), 'payment', ['flutterwave_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_flutterwave_id'), table_name='payment')
    op.drop_column('payment', 'updated_at')
    op.drop_column('payment', 'flutterwave_id')
    op.drop_column('payment', 'payment_method')
    op.drop_column('payment', 'currency')
    # ### end Alembic commands ###
