"""increase_image_length

Revision ID: 25639850801c
Revises: 2ff9d79e209
Create Date: 2026-04-14 11:32:25.040957

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '25639850801c'
down_revision = '2ff9d79e209'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'image',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('system_settings', 'association_logo',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('system_settings', 'association_logo',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('event', 'image',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###
