"""add organization credit models and fields

Revision ID: 2cb8a58be64c
Revises: fix_credit_transfer_cascade
Create Date: 2026-01-20 22:24:48.910499

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2cb8a58be64c'
down_revision = 'fix_credit_transfer_cascade'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_credit_transfer_recipient_user'), 'credit_transfer', type_='foreignkey')
    op.drop_constraint(op.f('fk_credit_transfer_sender_user'), 'credit_transfer', type_='foreignkey')
    op.create_foreign_key(None, 'credit_transfer', 'user', ['recipient_id'], ['id'])
    op.create_foreign_key(None, 'credit_transfer', 'user', ['sender_id'], ['id'])
    op.alter_column('organization_credit_transaction', 'description',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.drop_index(op.f('ix_organization_credit_transaction_workspace_id'), table_name='organization_credit_transaction')
    op.drop_column('organization_credit_transaction', 'reference_id')
    op.drop_index(op.f('ix_role_name'), table_name='role')
    op.create_index(op.f('ix_role_name'), 'role', ['name'], unique=False)
    op.drop_constraint(op.f('unique_workspace_period_usage'), 'workspace_usage_tracking', type_='unique')
    op.create_index(op.f('ix_workspace_usage_tracking_billing_period_end'), 'workspace_usage_tracking', ['billing_period_end'], unique=False)
    op.create_index(op.f('ix_workspace_usage_tracking_billing_period_start'), 'workspace_usage_tracking', ['billing_period_start'], unique=False)
    op.drop_column('workspace_usage_tracking', 'created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspace_usage_tracking', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_workspace_usage_tracking_billing_period_start'), table_name='workspace_usage_tracking')
    op.drop_index(op.f('ix_workspace_usage_tracking_billing_period_end'), table_name='workspace_usage_tracking')
    op.create_unique_constraint(op.f('unique_workspace_period_usage'), 'workspace_usage_tracking', ['workspace_id', 'billing_period_start'])
    op.drop_index(op.f('ix_role_name'), table_name='role')
    op.create_index(op.f('ix_role_name'), 'role', ['name'], unique=True)
    op.add_column('organization_credit_transaction', sa.Column('reference_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_organization_credit_transaction_workspace_id'), 'organization_credit_transaction', ['workspace_id'], unique=False)
    op.alter_column('organization_credit_transaction', 'description',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.drop_constraint(None, 'credit_transfer', type_='foreignkey')
    op.drop_constraint(None, 'credit_transfer', type_='foreignkey')
    op.create_foreign_key(op.f('fk_credit_transfer_sender_user'), 'credit_transfer', 'user', ['sender_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_credit_transfer_recipient_user'), 'credit_transfer', 'user', ['recipient_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
