"""Add organization_id and CopilotWorkspace

Revision ID: 32e6102dd038
Revises: 2cb8a58be64c
Create Date: 2026-01-25 09:29:14.674415

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '32e6102dd038'
down_revision = '2cb8a58be64c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('copilot_workspace',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('copilot_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['copilot_id'], ['copilot.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_copilot_workspace_copilot_id'), 'copilot_workspace', ['copilot_id'], unique=False)
    op.create_index(op.f('ix_copilot_workspace_workspace_id'), 'copilot_workspace', ['workspace_id'], unique=False)
    op.add_column('copilot', sa.Column('organization_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_copilot_organization_id'), 'copilot', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_copilot_organization_id'), table_name='copilot')
    op.drop_column('copilot', 'organization_id')
    op.drop_index(op.f('ix_copilot_workspace_workspace_id'), table_name='copilot_workspace')
    op.drop_index(op.f('ix_copilot_workspace_copilot_id'), table_name='copilot_workspace')
    op.drop_table('copilot_workspace')
    # ### end Alembic commands ###
