"""Add organization_id to Campaign

Revision ID: 36eb937fa518
Revises: a24b576829bc
Create Date: 2026-02-24 00:45:15.315091

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '36eb937fa518'
down_revision = 'a24b576829bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign', sa.Column('organization_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_campaign_organization_id'), 'campaign', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'campaign', 'organization', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'campaign', type_='foreignkey')
    op.drop_index(op.f('ix_campaign_organization_id'), table_name='campaign')
    op.drop_column('campaign', 'organization_id')
    # ### end Alembic commands ###
