"""Add wallet tables

Revision ID: 3f33d381c6dc
Revises: ff950ce044f6
Create Date: 2026-01-31 17:41:16.032649

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3f33d381c6dc'
down_revision = 'ff950ce044f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import inspect
    
    conn = op.get_bind()
    inspector = inspect(conn)
    
    # All table operations must be protected by inspector checks to avoid transaction failure
    tables = inspector.get_table_names()
    
    # 1. APIRequest safety
    if 'apirequest' in tables:
        apirequest_columns = [c['name'] for c in inspector.get_columns('apirequest')]
        if 'organization_id' not in apirequest_columns:
            op.add_column('apirequest', sa.Column('organization_id', sa.Uuid(), nullable=True))
            op.create_index(op.f('ix_apirequest_organization_id'), 'apirequest', ['organization_id'], unique=False)
            op.create_foreign_key(None, 'apirequest', 'organization', ['organization_id'], ['id'], ondelete='SET NULL')
    
    # 2. Audit Log safety
    if 'audit_log' in tables:
        al_fks = [f['name'] for f in inspector.get_foreign_keys('audit_log')]
        if op.f('audit_log_actor_id_fkey') in al_fks:
            op.drop_constraint(op.f('audit_log_actor_id_fkey'), 'audit_log', type_='foreignkey')
        op.create_foreign_key(None, 'audit_log', 'user', ['actor_id'], ['id'], ondelete='SET NULL')
    
    # 3. Credit Transfer safety
    if 'credit_transfer' in tables:
        ct_fks = [f['name'] for f in inspector.get_foreign_keys('credit_transfer')]
        if op.f('credit_transfer_recipient_id_fkey') in ct_fks:
            op.drop_constraint(op.f('credit_transfer_recipient_id_fkey'), 'credit_transfer', type_='foreignkey')
        if op.f('credit_transfer_sender_id_fkey') in ct_fks:
            op.drop_constraint(op.f('credit_transfer_sender_id_fkey'), 'credit_transfer', type_='foreignkey')
        op.create_foreign_key(None, 'credit_transfer', 'user', ['recipient_id'], ['id'], ondelete='CASCADE')
        op.create_foreign_key(None, 'credit_transfer', 'user', ['sender_id'], ['id'], ondelete='CASCADE')
    
    # 4. Platform Settings safety
    if 'platform_settings' in tables:
        ps_fks = [f['name'] for f in inspector.get_foreign_keys('platform_settings')]
        if op.f('platform_settings_updated_by_fkey') in ps_fks:
            op.drop_constraint(op.f('platform_settings_updated_by_fkey'), 'platform_settings', type_='foreignkey')
        op.create_foreign_key(None, 'platform_settings', 'user', ['updated_by'], ['id'], ondelete='SET NULL')
    
    # 5. TopUp safety
    if 'topup' in tables:
        topup_columns = [c['name'] for c in inspector.get_columns('topup')]
        if 'organization_id' not in topup_columns:
            op.add_column('topup', sa.Column('organization_id', sa.Uuid(), nullable=True))
            op.create_index(op.f('ix_topup_organization_id'), 'topup', ['organization_id'], unique=False)
            op.create_foreign_key(None, 'topup', 'organization', ['organization_id'], ['id'])
    
    # 6. Workspace Project safety
    if 'workspace_project' in tables:
        wp_fks = [f['name'] for f in inspector.get_foreign_keys('workspace_project')]
        if op.f('workspace_project_created_by_fkey') in wp_fks:
            op.drop_constraint(op.f('workspace_project_created_by_fkey'), 'workspace_project', type_='foreignkey')
        op.create_foreign_key(None, 'workspace_project', 'user', ['created_by'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspace_project', type_='foreignkey')
    op.create_foreign_key(op.f('workspace_project_created_by_fkey'), 'workspace_project', 'user', ['created_by'], ['id'])
    op.drop_constraint(None, 'topup', type_='foreignkey')
    op.drop_index(op.f('ix_topup_organization_id'), table_name='topup')
    op.drop_column('topup', 'organization_id')
    op.drop_constraint(None, 'platform_settings', type_='foreignkey')
    op.create_foreign_key(op.f('platform_settings_updated_by_fkey'), 'platform_settings', 'user', ['updated_by'], ['id'])
    op.drop_constraint(None, 'credit_transfer', type_='foreignkey')
    op.drop_constraint(None, 'credit_transfer', type_='foreignkey')
    op.create_foreign_key(op.f('credit_transfer_sender_id_fkey'), 'credit_transfer', 'user', ['sender_id'], ['id'])
    op.create_foreign_key(op.f('credit_transfer_recipient_id_fkey'), 'credit_transfer', 'user', ['recipient_id'], ['id'])
    op.drop_constraint(None, 'audit_log', type_='foreignkey')
    op.create_foreign_key(op.f('audit_log_actor_id_fkey'), 'audit_log', 'user', ['actor_id'], ['id'])
    op.drop_constraint(None, 'apirequest', type_='foreignkey')
    op.drop_index(op.f('ix_apirequest_organization_id'), table_name='apirequest')
    op.drop_column('apirequest', 'organization_id')
    # ### end Alembic commands ###
