"""add platform settings table

Revision ID: 6e602637289f
Revises: eb295549313b
Create Date: 2026-02-02 21:16:29.270692

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector


# revision identifiers, used by Alembic.
revision = '6e602637289f'
down_revision = 'eb295549313b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    
    # 1. Create schemas
    op.execute("CREATE SCHEMA IF NOT EXISTS copilot")
    
    # 2. Create platform_settings table if missing
    if 'platform_settings' not in inspector.get_table_names():
        op.create_table('platform_settings',
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.Column('general', sa.JSON(), nullable=True),
            sa.Column('notifications', sa.JSON(), nullable=True),
            sa.Column('payments', sa.JSON(), nullable=True),
            sa.Column('gateways', sa.JSON(), nullable=True),
            sa.Column('email', sa.JSON(), nullable=True),
            sa.Column('security', sa.JSON(), nullable=True),
            sa.Column('rate_limiting', sa.JSON(), nullable=True),
            sa.Column('integrations', sa.JSON(), nullable=True),
            sa.Column('compliance', sa.JSON(), nullable=True),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.Column('updated_by', sa.Uuid(), nullable=True),
            sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ondelete='SET NULL'),
            sa.PrimaryKeyConstraint('id')
        )
        
        # Insert default settings row if table is empty
        op.execute("""
            INSERT INTO platform_settings (id, general, notifications, payments, gateways, email, security, rate_limiting, integrations, compliance, updated_at)
            SELECT gen_random_uuid(), 
                   '{"platformName": "Qorebit Enterprise", "systemStatus": "active"}'::jsonb,
                   '{}'::jsonb, 
                   '{"minCreditAmount": 1000, "nairaToCreditRate": 1650, "enablePayments": true}'::jsonb,
                   '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb,
                   now()
            WHERE NOT EXISTS (SELECT 1 FROM platform_settings);
        """)

    # 3. Create security_event table if missing
    if 'security_event' not in inspector.get_table_names():
        op.create_table('security_event',
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.Column('type', sa.String(length=50), nullable=False),
            sa.Column('severity', sa.String(length=20), nullable=False),
            sa.Column('description', sa.String(length=500), nullable=False),
            sa.Column('source_ip', sa.String(length=50), nullable=True),
            sa.Column('location', sa.String(length=100), nullable=True),
            sa.Column('status', sa.String(length=20), nullable=False),
            sa.Column('user_id', sa.Uuid(), nullable=True),
            sa.Column('assigned_to_id', sa.Uuid(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('updated_at', sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(['assigned_to_id'], ['user.id'], ondelete='SET NULL'),
            sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_security_event_created_at'), 'security_event', ['created_at'], unique=False)
        op.create_index(op.f('ix_security_event_severity'), 'security_event', ['severity'], unique=False)
        op.create_index(op.f('ix_security_event_status'), 'security_event', ['status'], unique=False)
        op.create_index(op.f('ix_security_event_type'), 'security_event', ['type'], unique=False)

    # 4. Create copilot tables if missing
    if 'copilot' not in inspector.get_table_names(schema='copilot'):
        op.create_table('copilot',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('avatar', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column('visibility', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column('tags', sa.JSON(), nullable=True),
        sa.Column('model', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column('temperature', sa.Float(), nullable=False),
        sa.Column('max_tokens', sa.Integer(), nullable=False),
        sa.Column('top_p', sa.Float(), nullable=False),
        sa.Column('frequency_penalty', sa.Float(), nullable=False),
        sa.Column('presence_penalty', sa.Float(), nullable=False),
        sa.Column('stop_sequences', sa.JSON(), nullable=True),
        sa.Column('system_prompt', sa.Text(), nullable=True),
        sa.Column('welcome_message', sa.Text(), nullable=True),
        sa.Column('suggested_prompts', sa.JSON(), nullable=True),
        sa.Column('capabilities', sa.JSON(), nullable=True),
        sa.Column('allow_file_uploads', sa.Boolean(), nullable=False),
        sa.Column('allow_web_search', sa.Boolean(), nullable=False),
        sa.Column('allow_code_execution', sa.Boolean(), nullable=False),
        sa.Column('memory_enabled', sa.Boolean(), nullable=False),
        sa.Column('memory_window_size', sa.Integer(), nullable=False),
        sa.Column('tools_config', sa.JSON(), nullable=True),
        sa.Column('created_by', sa.Uuid(), nullable=False),
        sa.Column('organization_id', sa.Uuid(), nullable=True),
        sa.Column('workspace_id', sa.Uuid(), nullable=True),
        sa.Column('usage_count', sa.Integer(), nullable=False),
        sa.Column('rating', sa.Float(), nullable=True),
        sa.Column('is_featured', sa.Boolean(), nullable=False),
        sa.Column('is_official', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        schema='copilot'
        )
        op.create_index(op.f('ix_copilot_copilot_category'), 'copilot', ['category'], unique=False, schema='copilot')
        op.create_index(op.f('ix_copilot_copilot_created_at'), 'copilot', ['created_at'], unique=False, schema='copilot')
        op.create_index(op.f('ix_copilot_copilot_created_by'), 'copilot', ['created_by'], unique=False, schema='copilot')
        op.create_index(op.f('ix_copilot_copilot_name'), 'copilot', ['name'], unique=False, schema='copilot')
        op.create_index(op.f('ix_copilot_copilot_organization_id'), 'copilot', ['organization_id'], unique=False, schema='copilot')
        op.create_index(op.f('ix_copilot_copilot_status'), 'copilot', ['status'], unique=False, schema='copilot')
        op.create_index(op.f('ix_copilot_copilot_visibility'), 'copilot', ['visibility'], unique=False, schema='copilot')
        op.create_index(op.f('ix_copilot_copilot_workspace_id'), 'copilot', ['workspace_id'], unique=False, schema='copilot')
        op.create_table('copilot_activity',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('copilot_id', sa.Uuid(), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('activity_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column('activity_status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
        sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column('activity_metadata', sa.JSON(), nullable=True),
        sa.Column('unique_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['copilot_id'], ['copilot.copilot.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        schema='copilot'
        )
        op.create_index(op.f('ix_copilot_copilot_activity_activity_status'), 'copilot_activity', ['activity_status'], unique=False, schema='copilot')
        op.create_index(op.f('ix_copilot_copilot_activity_activity_type'), 'copilot_activity', ['activity_type'], unique=False, schema='copilot')
        op.create_index(op.f('ix_copilot_copilot_activity_copilot_id'), 'copilot_activity', ['copilot_id'], unique=False, schema='copilot')
        op.create_index(op.f('ix_copilot_copilot_activity_created_at'), 'copilot_activity', ['created_at'], unique=False, schema='copilot')
        op.create_index(op.f('ix_copilot_copilot_activity_user_id'), 'copilot_activity', ['user_id'], unique=False, schema='copilot')
        op.create_table('copilot_conversation',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('copilot_id', sa.Uuid(), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('context', sa.JSON(), nullable=True),
        sa.Column('memory_summary', sa.Text(), nullable=True),
        sa.Column('message_count', sa.Integer(), nullable=False),
        sa.Column('total_tokens_used', sa.Integer(), nullable=False),
        sa.Column('total_cost', sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('last_message_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['copilot_id'], ['copilot.copilot.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        schema='copilot'
        )
        op.create_index(op.f('ix_copilot_copilot_conversation_copilot_id'), 'copilot_conversation', ['copilot_id'], unique=False, schema='copilot')
        op.create_index(op.f('ix_copilot_copilot_conversation_created_at'), 'copilot_conversation', ['created_at'], unique=False, schema='copilot')
        op.create_index(op.f('ix_copilot_copilot_conversation_user_id'), 'copilot_conversation', ['user_id'], unique=False, schema='copilot')
        op.create_table('copilot_document',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('copilot_id', sa.Uuid(), nullable=False),
        sa.Column('uploaded_by', sa.Uuid(), nullable=False),
        sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.Column('file_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column('file_size', sa.Integer(), nullable=False),
        sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
        sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
        sa.Column('document_metadata', sa.JSON(), nullable=True),
        sa.Column('total_chunks', sa.Integer(), nullable=False),
        sa.Column('total_tokens', sa.Integer(), nullable=False),
        sa.Column('processing_started_at', sa.DateTime(), nullable=True),
        sa.Column('processing_completed_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['copilot_id'], ['copilot.copilot.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        schema='copilot'
        )
        op.create_index(op.f('ix_copilot_copilot_document_copilot_id'), 'copilot_document', ['copilot_id'], unique=False, schema='copilot')
        op.create_index(op.f('ix_copilot_copilot_document_created_at'), 'copilot_document', ['created_at'], unique=False, schema='copilot')
        op.create_index(op.f('ix_copilot_copilot_document_status'), 'copilot_document', ['status'], unique=False, schema='copilot')
        op.create_index(op.f('ix_copilot_copilot_document_uploaded_by'), 'copilot_document', ['uploaded_by'], unique=False, schema='copilot')
        op.create_table('copilot_share',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('copilot_id', sa.Uuid(), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=True),
        sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('message', sa.Text(), nullable=True),
        sa.Column('can_edit', sa.Boolean(), nullable=False),
        sa.Column('can_chat', sa.Boolean(), nullable=False),
        sa.Column('shared_by', sa.Uuid(), nullable=False),
        sa.Column('shared_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['copilot_id'], ['copilot.copilot.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        schema='copilot'
        )
        op.create_index(op.f('ix_copilot_copilot_share_copilot_id'), 'copilot_share', ['copilot_id'], unique=False, schema='copilot')
        op.create_index(op.f('ix_copilot_copilot_share_email'), 'copilot_share', ['email'], unique=False, schema='copilot')
        op.create_index(op.f('ix_copilot_copilot_share_shared_at'), 'copilot_share', ['shared_at'], unique=False, schema='copilot')
        op.create_index(op.f('ix_copilot_copilot_share_user_id'), 'copilot_share', ['user_id'], unique=False, schema='copilot')
        op.create_table('copilot_tool',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('copilot_id', sa.Uuid(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
        sa.Column('tool_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column('parameters_schema', sa.JSON(), nullable=True),
        sa.Column('config', sa.JSON(), nullable=True),
        sa.Column('is_enabled', sa.Boolean(), nullable=False),
        sa.Column('requires_confirmation', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['copilot_id'], ['copilot.copilot.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        schema='copilot'
        )
        op.create_index(op.f('ix_copilot_copilot_tool_copilot_id'), 'copilot_tool', ['copilot_id'], unique=False, schema='copilot')
        op.create_index(op.f('ix_copilot_copilot_tool_name'), 'copilot_tool', ['name'], unique=False, schema='copilot')
        op.create_index(op.f('ix_copilot_copilot_tool_tool_type'), 'copilot_tool', ['tool_type'], unique=False, schema='copilot')
        op.create_table('copilot_workspace',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('copilot_id', sa.Uuid(), nullable=False),
        sa.Column('workspace_id', sa.Uuid(), nullable=False),
        sa.Column('assigned_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['copilot_id'], ['copilot.copilot.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        schema='copilot'
        )
        op.create_index(op.f('ix_copilot_copilot_workspace_copilot_id'), 'copilot_workspace', ['copilot_id'], unique=False, schema='copilot')
        op.create_index(op.f('ix_copilot_copilot_workspace_workspace_id'), 'copilot_workspace', ['workspace_id'], unique=False, schema='copilot')
        op.create_table('copilot_document_chunk',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('document_id', sa.Uuid(), nullable=False),
        sa.Column('chunk_index', sa.Integer(), nullable=False),
        sa.Column('content', sa.Text(), nullable=True),
        sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
        sa.Column('start_char', sa.Integer(), nullable=True),
        sa.Column('end_char', sa.Integer(), nullable=True),
        sa.Column('page_number', sa.Integer(), nullable=True),
        sa.Column('section', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column('chunk_metadata', sa.JSON(), nullable=True),
        sa.Column('token_count', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['document_id'], ['copilot.copilot_document.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        schema='copilot'
        )
        op.create_index(op.f('ix_copilot_copilot_document_chunk_document_id'), 'copilot_document_chunk', ['document_id'], unique=False, schema='copilot')
        op.create_table('copilot_execution',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('copilot_id', sa.Uuid(), nullable=False),
        sa.Column('conversation_id', sa.Uuid(), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('celery_task_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column('input_message', sa.Text(), nullable=True),
        sa.Column('output_response', sa.Text(), nullable=True),
        sa.Column('model_used', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column('total_tokens', sa.Integer(), nullable=False),
        sa.Column('total_cost', sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
        sa.Column('retry_count', sa.Integer(), nullable=False),
        sa.Column('max_retries', sa.Integer(), nullable=False),
        sa.Column('started_at', sa.DateTime(), nullable=True),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.Column('execution_time_ms', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['conversation_id'], ['copilot.copilot_conversation.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['copilot_id'], ['copilot.copilot.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        schema='copilot'
        )
        op.create_index(op.f('ix_copilot_copilot_execution_celery_task_id'), 'copilot_execution', ['celery_task_id'], unique=False, schema='copilot')
        op.create_index(op.f('ix_copilot_copilot_execution_conversation_id'), 'copilot_execution', ['conversation_id'], unique=False, schema='copilot')
        op.create_index(op.f('ix_copilot_copilot_execution_copilot_id'), 'copilot_execution', ['copilot_id'], unique=False, schema='copilot')
        op.create_index(op.f('ix_copilot_copilot_execution_created_at'), 'copilot_execution', ['created_at'], unique=False, schema='copilot')
        op.create_index(op.f('ix_copilot_copilot_execution_status'), 'copilot_execution', ['status'], unique=False, schema='copilot')
        op.create_index(op.f('ix_copilot_copilot_execution_user_id'), 'copilot_execution', ['user_id'], unique=False, schema='copilot')
        op.create_table('copilot_message',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('conversation_id', sa.Uuid(), nullable=False),
        sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column('content', sa.Text(), nullable=True),
        sa.Column('tool_calls', sa.JSON(), nullable=True),
        sa.Column('tool_call_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column('attachments', sa.JSON(), nullable=True),
        sa.Column('message_metadata', sa.JSON(), nullable=True),
        sa.Column('model_used', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column('tokens_used', sa.Integer(), nullable=True),
        sa.Column('cost', sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column('response_time_ms', sa.Integer(), nullable=True),
        sa.Column('agent_steps', sa.JSON(), nullable=True),
        sa.Column('feedback_rating', sa.Integer(), nullable=True),
        sa.Column('feedback_comment', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['conversation_id'], ['copilot.copilot_conversation.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        schema='copilot'
        )
        op.create_index(op.f('ix_copilot_copilot_message_conversation_id'), 'copilot_message', ['conversation_id'], unique=False, schema='copilot')
        op.create_index(op.f('ix_copilot_copilot_message_created_at'), 'copilot_message', ['created_at'], unique=False, schema='copilot')
        op.create_index(op.f('ix_copilot_copilot_message_role'), 'copilot_message', ['role'], unique=False, schema='copilot')
        op.create_table('copilot_tool_execution',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('tool_id', sa.Uuid(), nullable=False),
        sa.Column('conversation_id', sa.Uuid(), nullable=False),
        sa.Column('message_id', sa.Uuid(), nullable=True),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column('input_params', sa.JSON(), nullable=True),
        sa.Column('output_result', sa.JSON(), nullable=True),
        sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
        sa.Column('started_at', sa.DateTime(), nullable=True),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.Column('execution_time_ms', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['conversation_id'], ['copilot.copilot_conversation.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['message_id'], ['copilot.copilot_message.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['tool_id'], ['copilot.copilot_tool.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        schema='copilot'
        )
        op.create_index(op.f('ix_copilot_copilot_tool_execution_conversation_id'), 'copilot_tool_execution', ['conversation_id'], unique=False, schema='copilot')
        op.create_index(op.f('ix_copilot_copilot_tool_execution_created_at'), 'copilot_tool_execution', ['created_at'], unique=False, schema='copilot')
        op.create_index(op.f('ix_copilot_copilot_tool_execution_status'), 'copilot_tool_execution', ['status'], unique=False, schema='copilot')
        op.create_index(op.f('ix_copilot_copilot_tool_execution_tool_id'), 'copilot_tool_execution', ['tool_id'], unique=False, schema='copilot')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_copilot_copilot_tool_execution_tool_id'), table_name='copilot_tool_execution', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_tool_execution_status'), table_name='copilot_tool_execution', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_tool_execution_created_at'), table_name='copilot_tool_execution', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_tool_execution_conversation_id'), table_name='copilot_tool_execution', schema='copilot')
    op.drop_table('copilot_tool_execution', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_message_role'), table_name='copilot_message', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_message_created_at'), table_name='copilot_message', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_message_conversation_id'), table_name='copilot_message', schema='copilot')
    op.drop_table('copilot_message', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_execution_user_id'), table_name='copilot_execution', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_execution_status'), table_name='copilot_execution', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_execution_created_at'), table_name='copilot_execution', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_execution_copilot_id'), table_name='copilot_execution', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_execution_conversation_id'), table_name='copilot_execution', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_execution_celery_task_id'), table_name='copilot_execution', schema='copilot')
    op.drop_table('copilot_execution', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_document_chunk_document_id'), table_name='copilot_document_chunk', schema='copilot')
    op.drop_table('copilot_document_chunk', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_workspace_workspace_id'), table_name='copilot_workspace', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_workspace_copilot_id'), table_name='copilot_workspace', schema='copilot')
    op.drop_table('copilot_workspace', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_tool_tool_type'), table_name='copilot_tool', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_tool_name'), table_name='copilot_tool', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_tool_copilot_id'), table_name='copilot_tool', schema='copilot')
    op.drop_table('copilot_tool', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_share_user_id'), table_name='copilot_share', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_share_shared_at'), table_name='copilot_share', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_share_email'), table_name='copilot_share', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_share_copilot_id'), table_name='copilot_share', schema='copilot')
    op.drop_table('copilot_share', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_document_uploaded_by'), table_name='copilot_document', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_document_status'), table_name='copilot_document', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_document_created_at'), table_name='copilot_document', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_document_copilot_id'), table_name='copilot_document', schema='copilot')
    op.drop_table('copilot_document', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_conversation_user_id'), table_name='copilot_conversation', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_conversation_created_at'), table_name='copilot_conversation', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_conversation_copilot_id'), table_name='copilot_conversation', schema='copilot')
    op.drop_table('copilot_conversation', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_activity_user_id'), table_name='copilot_activity', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_activity_created_at'), table_name='copilot_activity', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_activity_copilot_id'), table_name='copilot_activity', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_activity_activity_type'), table_name='copilot_activity', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_activity_activity_status'), table_name='copilot_activity', schema='copilot')
    op.drop_table('copilot_activity', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_workspace_id'), table_name='copilot', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_visibility'), table_name='copilot', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_status'), table_name='copilot', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_organization_id'), table_name='copilot', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_name'), table_name='copilot', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_created_by'), table_name='copilot', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_created_at'), table_name='copilot', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_category'), table_name='copilot', schema='copilot')
    op.drop_table('copilot', schema='copilot')
    # ### end Alembic commands ###
