"""add_campaign_table

Revision ID: 8376ab50ddcb
Revises: 9b12cd44e922
Create Date: 2026-01-08 12:46:01.902313

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8376ab50ddcb'
down_revision = '9b12cd44e922'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('recipients', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_created_at'), 'campaign', ['created_at'], unique=False)
    op.create_index(op.f('ix_campaign_name'), 'campaign', ['name'], unique=False)
    op.create_index(op.f('ix_campaign_status'), 'campaign', ['status'], unique=False)
    op.create_index(op.f('ix_campaign_user_id'), 'campaign', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaign_user_id'), table_name='campaign')
    op.drop_index(op.f('ix_campaign_status'), table_name='campaign')
    op.drop_index(op.f('ix_campaign_name'), table_name='campaign')
    op.drop_index(op.f('ix_campaign_created_at'), table_name='campaign')
    op.drop_table('campaign')
    # ### end Alembic commands ###
