"""Add TopUp and APIKey models

Revision ID: 88257c6a1c9c
Revises: 27eb9b266e47
Create Date: 2025-11-20 10:10:46.940880

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '88257c6a1c9c'
down_revision = 'f9664f1acfcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apikey',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('key_prefix', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('key_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apikey_created_at'), 'apikey', ['created_at'], unique=False)
    op.create_index(op.f('ix_apikey_user_id'), 'apikey', ['user_id'], unique=False)
    op.create_table('credit_transaction',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('transaction_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('reference_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_transaction_created_at'), 'credit_transaction', ['created_at'], unique=False)
    op.create_index(op.f('ix_credit_transaction_transaction_type'), 'credit_transaction', ['transaction_type'], unique=False)
    op.create_index(op.f('ix_credit_transaction_user_id'), 'credit_transaction', ['user_id'], unique=False)
    op.create_table('topup',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('amount_naira', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ai_credits', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'EXPIRED', name='topupstatus'), nullable=False),
    sa.Column('payment_reference', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('monnify_reference', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('account_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('bank_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('payment_method', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topup_created_at'), 'topup', ['created_at'], unique=False)
    op.create_index(op.f('ix_topup_payment_reference'), 'topup', ['payment_reference'], unique=True)
    op.create_index(op.f('ix_topup_user_id'), 'topup', ['user_id'], unique=False)
    op.drop_index(op.f('ix_credittransaction_created_at'), table_name='credittransaction')
    op.drop_index(op.f('ix_credittransaction_transaction_type'), table_name='credittransaction')
    op.drop_index(op.f('ix_credittransaction_user_id'), table_name='credittransaction')
    op.drop_table('credittransaction')
    # Skip credit_transfer changes - not critical for TopUp/APIKey functionality
    # These changes can be applied in a separate migration if needed
    # op.alter_column('credit_transfer', 'status',
    #            existing_type=sa.VARCHAR(length=20),
    #            type_=sa.Enum('COMPLETED', 'PENDING', 'FAILED', name='transactionstatus'),
    #            existing_nullable=False,
    #            existing_server_default=sa.text("'Pending'::character varying"))
    # op.alter_column('credit_transfer', 'created_at',
    #            existing_type=postgresql.TIMESTAMP(timezone=True),
    #            type_=sa.DateTime(),
    #            existing_nullable=False,
    #            existing_server_default=sa.text('now()'))
    # op.alter_column('credit_transfer', 'updated_at',
    #            existing_type=postgresql.TIMESTAMP(timezone=True),
    #            type_=sa.DateTime(),
    #            existing_nullable=False,
    #            existing_server_default=sa.text('now()'))
    # op.drop_index(op.f('ix_credit_transfer_created_at'), table_name='credit_transfer')
    # op.drop_index(op.f('ix_credit_transfer_recipient_id'), table_name='credit_transfer')
    # op.drop_index(op.f('ix_credit_transfer_sender_id'), table_name='credit_transfer')
    # op.drop_index(op.f('ix_credit_transfer_status'), table_name='credit_transfer')
    # op.drop_constraint(op.f('credit_transfer_sender_id_fkey'), 'credit_transfer', type_='foreignkey')
    # op.drop_constraint(op.f('credit_transfer_recipient_id_fkey'), 'credit_transfer', type_='foreignkey')
    # op.create_foreign_key(None, 'credit_transfer', 'user', ['sender_id'], ['id'])
    # op.create_foreign_key(None, 'credit_transfer', 'user', ['recipient_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Commented out credit_transfer rollback - skipped in upgrade
    # op.drop_constraint(None, 'credit_transfer', type_='foreignkey')
    # op.drop_constraint(None, 'credit_transfer', type_='foreignkey')
    # op.create_foreign_key(op.f('credit_transfer_recipient_id_fkey'), 'credit_transfer', 'user', ['recipient_id'], ['id'], ondelete='CASCADE')
    # op.create_foreign_key(op.f('credit_transfer_sender_id_fkey'), 'credit_transfer', 'user', ['sender_id'], ['id'], ondelete='CASCADE')
    # op.create_index(op.f('ix_credit_transfer_status'), 'credit_transfer', ['status'], unique=False)
    # op.create_index(op.f('ix_credit_transfer_sender_id'), 'credit_transfer', ['sender_id'], unique=False)
    # op.create_index(op.f('ix_credit_transfer_recipient_id'), 'credit_transfer', ['recipient_id'], unique=False)
    # op.create_index(op.f('ix_credit_transfer_created_at'), 'credit_transfer', ['created_at'], unique=False)
    # op.alter_column('credit_transfer', 'updated_at',
    #            existing_type=sa.DateTime(),
    #            type_=postgresql.TIMESTAMP(timezone=True),
    #            existing_nullable=False,
    #            existing_server_default=sa.text('now()'))
    # op.alter_column('credit_transfer', 'created_at',
    #            existing_type=sa.DateTime(),
    #            type_=postgresql.TIMESTAMP(timezone=True),
    #            existing_nullable=False,
    #            existing_server_default=sa.text('now()'))
    # op.alter_column('credit_transfer', 'status',
    #            existing_type=sa.Enum('COMPLETED', 'PENDING', 'FAILED', name='transactionstatus'),
    #            type_=sa.VARCHAR(length=20),
    #            existing_nullable=False,
    #            existing_server_default=sa.text("'Pending'::character varying"))
    op.create_table('credittransaction',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('balance_after', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('reference_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('credittransaction_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('credittransaction_pkey'))
    )
    op.create_index(op.f('ix_credittransaction_user_id'), 'credittransaction', ['user_id'], unique=False)
    op.create_index(op.f('ix_credittransaction_transaction_type'), 'credittransaction', ['transaction_type'], unique=False)
    op.create_index(op.f('ix_credittransaction_created_at'), 'credittransaction', ['created_at'], unique=False)
    op.drop_index(op.f('ix_topup_user_id'), table_name='topup')
    op.drop_index(op.f('ix_topup_payment_reference'), table_name='topup')
    op.drop_index(op.f('ix_topup_created_at'), table_name='topup')
    op.drop_table('topup')
    op.drop_index(op.f('ix_credit_transaction_user_id'), table_name='credit_transaction')
    op.drop_index(op.f('ix_credit_transaction_transaction_type'), table_name='credit_transaction')
    op.drop_index(op.f('ix_credit_transaction_created_at'), table_name='credit_transaction')
    op.drop_table('credit_transaction')
    op.drop_index(op.f('ix_apikey_user_id'), table_name='apikey')
    op.drop_index(op.f('ix_apikey_created_at'), table_name='apikey')
    op.drop_table('apikey')
    # ### end Alembic commands ###
