"""add_aimodel_and_aiprovider

Revision ID: 8a96ee33d811
Revises: add_timezone_user
Create Date: 2026-01-03 18:57:59.732321

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8a96ee33d811'
down_revision = 'add_timezone_user'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aiprovider',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aiprovider_name'), 'aiprovider', ['name'], unique=True)
    op.create_index(op.f('ix_aiprovider_slug'), 'aiprovider', ['slug'], unique=True)
    op.create_table('aimodel',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('context_size', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('input_price', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('output_price', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('availability', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('best_use_cases', sa.JSON(), nullable=True),
    sa.Column('token_limits', sa.JSON(), nullable=True),
    sa.Column('compliance', sa.JSON(), nullable=True),
    sa.Column('lifecycle', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['aiprovider.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aimodel_name'), 'aimodel', ['name'], unique=False)
    op.create_index(op.f('ix_aimodel_slug'), 'aimodel', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aimodel_slug'), table_name='aimodel')
    op.drop_index(op.f('ix_aimodel_name'), table_name='aimodel')
    op.drop_table('aimodel')
    op.drop_index(op.f('ix_aiprovider_slug'), table_name='aiprovider')
    op.drop_index(op.f('ix_aiprovider_name'), table_name='aiprovider')
    op.drop_table('aiprovider')
    # ### end Alembic commands ###
