"""add_workspace_tables

Revision ID: 93510c4de6e8
Revises: add_user_settings_fields
Create Date: 2025-12-04 00:10:20.880093

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '93510c4de6e8'
down_revision = 'add_user_settings_fields'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('avatar', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('credits_balance', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_name'), 'workspace', ['name'], unique=False)
    op.create_index(op.f('ix_workspace_owner_id'), 'workspace', ['owner_id'], unique=False)
    op.create_table('workspace_member',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('credits_allocated', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_member_user_id'), 'workspace_member', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspace_member_workspace_id'), 'workspace_member', ['workspace_id'], unique=False)
    op.create_table('workspace_project',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('credits_used', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('api_calls_count', sa.Integer(), nullable=False),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_project_name'), 'workspace_project', ['name'], unique=False)
    op.create_index(op.f('ix_workspace_project_workspace_id'), 'workspace_project', ['workspace_id'], unique=False)
    op.create_table('workspace_role',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_role_name'), 'workspace_role', ['name'], unique=False)
    op.create_index(op.f('ix_workspace_role_workspace_id'), 'workspace_role', ['workspace_id'], unique=False)
    op.create_table('workspace_credit_transaction',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recipient_id', sa.Uuid(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['workspace_member.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_credit_transaction_workspace_id'), 'workspace_credit_transaction', ['workspace_id'], unique=False)
    op.create_table('workspace_member_role',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['workspace_member.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['workspace_role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_member_role_member_id'), 'workspace_member_role', ['member_id'], unique=False)
    op.create_index(op.f('ix_workspace_member_role_role_id'), 'workspace_member_role', ['role_id'], unique=False)
    op.create_table('workspace_project_member',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['workspace_member.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['workspace_project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_project_member_member_id'), 'workspace_project_member', ['member_id'], unique=False)
    op.create_index(op.f('ix_workspace_project_member_project_id'), 'workspace_project_member', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspace_project_member_project_id'), table_name='workspace_project_member')
    op.drop_index(op.f('ix_workspace_project_member_member_id'), table_name='workspace_project_member')
    op.drop_table('workspace_project_member')
    op.drop_index(op.f('ix_workspace_member_role_role_id'), table_name='workspace_member_role')
    op.drop_index(op.f('ix_workspace_member_role_member_id'), table_name='workspace_member_role')
    op.drop_table('workspace_member_role')
    op.drop_index(op.f('ix_workspace_credit_transaction_workspace_id'), table_name='workspace_credit_transaction')
    op.drop_table('workspace_credit_transaction')
    op.drop_index(op.f('ix_workspace_role_workspace_id'), table_name='workspace_role')
    op.drop_index(op.f('ix_workspace_role_name'), table_name='workspace_role')
    op.drop_table('workspace_role')
    op.drop_index(op.f('ix_workspace_project_workspace_id'), table_name='workspace_project')
    op.drop_index(op.f('ix_workspace_project_name'), table_name='workspace_project')
    op.drop_table('workspace_project')
    op.drop_index(op.f('ix_workspace_member_workspace_id'), table_name='workspace_member')
    op.drop_index(op.f('ix_workspace_member_user_id'), table_name='workspace_member')
    op.drop_table('workspace_member')
    op.drop_index(op.f('ix_workspace_owner_id'), table_name='workspace')
    op.drop_index(op.f('ix_workspace_name'), table_name='workspace')
    op.drop_table('workspace')
    # ### end Alembic commands ###
