"""Add ip_address and origin to apirequest

Revision ID: a2d13ee57700
Revises: a53f0a07fa4c
Create Date: 2026-02-16 13:27:41.853777

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a2d13ee57700'
down_revision = 'a53f0a07fa4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apikey', sa.Column('allowed_ips', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('apikey', sa.Column('allowed_domains', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('apirequest', sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('apirequest', sa.Column('origin', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # Check if index exists before creating
    # op.create_index(op.f('ix_apirequest_user_id'), 'apirequest', ['user_id'], unique=False)
    # op.create_index(op.f('ix_user_created_at'), 'user', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_created_at'), table_name='user')
    op.drop_index(op.f('ix_apirequest_user_id'), table_name='apirequest')
    op.drop_column('apirequest', 'origin')
    op.drop_column('apirequest', 'ip_address')
    op.drop_column('apikey', 'allowed_domains')
    op.drop_column('apikey', 'allowed_ips')
    op.drop_index(op.f('ix_copilot_copilot_tool_execution_tool_id'), table_name='copilot_tool_execution', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_tool_execution_status'), table_name='copilot_tool_execution', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_tool_execution_created_at'), table_name='copilot_tool_execution', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_tool_execution_conversation_id'), table_name='copilot_tool_execution', schema='copilot')
    op.drop_table('copilot_tool_execution', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_message_role'), table_name='copilot_message', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_message_created_at'), table_name='copilot_message', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_message_conversation_id'), table_name='copilot_message', schema='copilot')
    op.drop_table('copilot_message', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_execution_user_id'), table_name='copilot_execution', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_execution_status'), table_name='copilot_execution', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_execution_created_at'), table_name='copilot_execution', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_execution_copilot_id'), table_name='copilot_execution', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_execution_conversation_id'), table_name='copilot_execution', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_execution_celery_task_id'), table_name='copilot_execution', schema='copilot')
    op.drop_table('copilot_execution', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_document_chunk_document_id'), table_name='copilot_document_chunk', schema='copilot')
    op.drop_table('copilot_document_chunk', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_workspace_workspace_id'), table_name='copilot_workspace', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_workspace_copilot_id'), table_name='copilot_workspace', schema='copilot')
    op.drop_table('copilot_workspace', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_tool_tool_type'), table_name='copilot_tool', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_tool_name'), table_name='copilot_tool', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_tool_copilot_id'), table_name='copilot_tool', schema='copilot')
    op.drop_table('copilot_tool', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_share_user_id'), table_name='copilot_share', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_share_shared_at'), table_name='copilot_share', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_share_email'), table_name='copilot_share', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_share_copilot_id'), table_name='copilot_share', schema='copilot')
    op.drop_table('copilot_share', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_document_uploaded_by'), table_name='copilot_document', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_document_status'), table_name='copilot_document', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_document_created_at'), table_name='copilot_document', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_document_copilot_id'), table_name='copilot_document', schema='copilot')
    op.drop_table('copilot_document', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_conversation_user_id'), table_name='copilot_conversation', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_conversation_created_at'), table_name='copilot_conversation', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_conversation_copilot_id'), table_name='copilot_conversation', schema='copilot')
    op.drop_table('copilot_conversation', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_activity_user_id'), table_name='copilot_activity', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_activity_created_at'), table_name='copilot_activity', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_activity_copilot_id'), table_name='copilot_activity', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_activity_activity_type'), table_name='copilot_activity', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_activity_activity_status'), table_name='copilot_activity', schema='copilot')
    op.drop_table('copilot_activity', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_workspace_id'), table_name='copilot', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_visibility'), table_name='copilot', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_status'), table_name='copilot', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_organization_id'), table_name='copilot', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_name'), table_name='copilot', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_created_by'), table_name='copilot', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_created_at'), table_name='copilot', schema='copilot')
    op.drop_index(op.f('ix_copilot_copilot_category'), table_name='copilot', schema='copilot')
    op.drop_table('copilot', schema='copilot')
    # ### end Alembic commands ###
