"""phase3_alumni_transition_last

Revision ID: ab55fad7e951
Revises: 36eb937fa518
Create Date: 2026-04-03 07:33:56.458369

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ab55fad7e951'
down_revision = '36eb937fa518'
branch_labels = None
depends_on = None


def upgrade():
    # 1. Drop legacy tables with CASCADE to handle complex dependencies
    legacy_tables = [
        'helparticle', 'workspace_credit_transaction', 'workspace_usage_tracking', 
        'audit_log', 'helpfaq', 'organization_member', 'ai_chat_messages', 'campaign', 
        'topup', 'apikey', 'oauth_connection', 'organization_model', 'workspace_project', 
        'wallet_transaction', 'organization_credit_transaction', 'wallet', 'credit_transaction', 
        'workspace_member_role', 'workspace_project_member', 'platform_settings', 
        'workspace_role', 'aiprovider', 'credit_transfer', 'project', 'workspace', 
        'notification', 'security_event', 'apirequest', 'helpcategory', 'workspace_member', 
        'ai_chats', 'aimodel', 'organization'
    ]
    for table in legacy_tables:
        op.execute(sa.text(f'DROP TABLE IF EXISTS "{table}" CASCADE'))

    # 2. Clean up Role table (remove organization_id)
    op.execute(sa.text('ALTER TABLE "role" DROP COLUMN IF EXISTS "organization_id" CASCADE'))

    # 3. Create new tables for FGCEOSA
    op.create_table('announcement',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_announcement_created_at'), 'announcement', ['created_at'], unique=False)
    
    op.create_table('event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('payment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('transaction_reference', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_created_at'), 'payment', ['created_at'], unique=False)
    op.create_index(op.f('ix_payment_transaction_reference'), 'payment', ['transaction_reference'], unique=True)
    op.create_index(op.f('ix_payment_user_id'), 'payment', ['user_id'], unique=False)
    # 4. Update User table
    op.add_column('user', sa.Column('graduation_year', sqlmodel.sql.sqltypes.AutoString(length=4), nullable=True))
    op.add_column('user', sa.Column('profession', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('user', sa.Column('membership_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.execute(sa.text('DROP INDEX IF EXISTS "ix_user_tag_number"'))
    op.create_index(op.f('ix_user_membership_id'), 'user', ['membership_id'], unique=True)
    
    # Safely drop columns
    for col in ['tag_number', 'organization_name', 'account_type']:
        op.execute(sa.text(f'ALTER TABLE "user" DROP COLUMN IF EXISTS "{col}"'))
    # ### end Alembic commands ###

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('account_type', sa.VARCHAR(length=50), server_default=sa.text("'individual'::character varying"), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('organization_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('tag_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_user_membership_id'), table_name='user')
    op.create_index(op.f('ix_user_tag_number'), 'user', ['tag_number'], unique=True)
    op.drop_column('user', 'membership_id')
    op.drop_column('user', 'profession')
    op.drop_column('user', 'graduation_year')
    op.add_column('role', sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('role_organization_id_fkey'), 'role', 'organization', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_role_organization_id'), 'role', ['organization_id'], unique=False)
    op.create_table('credit_transaction',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('balance_after', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('reference_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('credit_transaction_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('credit_transaction_pkey'))
    )
    op.create_index(op.f('ix_credit_transaction_user_id'), 'credit_transaction', ['user_id'], unique=False)
    op.create_index(op.f('ix_credit_transaction_transaction_type'), 'credit_transaction', ['transaction_type'], unique=False)
    op.create_index(op.f('ix_credit_transaction_created_at'), 'credit_transaction', ['created_at'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('actor_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('actor_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('actor_role', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('actor_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('action_category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('target_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('target_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('severity', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('meta_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('correlation_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('request_source', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('auth_method', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], name=op.f('audit_log_actor_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_log_pkey'))
    )
    op.create_index(op.f('ix_audit_log_workspace_id'), 'audit_log', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_log_target_id'), 'audit_log', ['target_id'], unique=False)
    op.create_index(op.f('ix_audit_log_organization_id'), 'audit_log', ['organization_id'], unique=False)
    op.create_index(op.f('ix_audit_log_correlation_id'), 'audit_log', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_log_actor_id'), 'audit_log', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_table('helparticle',
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['helpcategory.id'], name=op.f('helparticle_category_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('helparticle_pkey'))
    )
    op.create_table('apirequest',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('endpoint', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('request_tokens', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('response_tokens', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('total_tokens', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('cost', sa.NUMERIC(precision=10, scale=4), server_default=sa.text('0.0000'), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'success'::character varying"), autoincrement=False, nullable=False),
    sa.Column('response_time_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('origin', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('apirequest_organization_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('apirequest_project_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('apirequest_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('apirequest_pkey'))
    )
    op.create_index(op.f('ix_apirequest_user_id'), 'apirequest', ['user_id'], unique=False)
    op.create_index(op.f('ix_apirequest_organization_id'), 'apirequest', ['organization_id'], unique=False)
    op.create_index(op.f('ix_apirequest_model'), 'apirequest', ['model'], unique=False)
    op.create_index(op.f('ix_apirequest_created_at'), 'apirequest', ['created_at'], unique=False)
    op.create_table('aimodel',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('provider_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('context_size', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('input_price', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=False),
    sa.Column('output_price', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=False),
    sa.Column('capabilities', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('availability', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('best_use_cases', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('token_limits', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('compliance', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('lifecycle', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['aiprovider.id'], name=op.f('aimodel_provider_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('aimodel_pkey'))
    )
    op.create_index(op.f('ix_aimodel_slug'), 'aimodel', ['slug'], unique=True)
    op.create_index(op.f('ix_aimodel_name'), 'aimodel', ['name'], unique=False)
    op.create_table('topup',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('amount_naira', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('ai_credits', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'COMPLETED', 'FAILED', 'EXPIRED', name='topupstatus'), autoincrement=False, nullable=False),
    sa.Column('payment_reference', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('monnify_reference', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('account_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('bank_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('payment_method', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('paid_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('topup_organization_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('topup_user_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('topup_workspace_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('topup_pkey'))
    )
    op.create_index(op.f('ix_topup_workspace_id'), 'topup', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_topup_user_id'), 'topup', ['user_id'], unique=False)
    op.create_index(op.f('ix_topup_payment_reference'), 'topup', ['payment_reference'], unique=True)
    op.create_index(op.f('ix_topup_organization_id'), 'topup', ['organization_id'], unique=False)
    op.create_index(op.f('ix_topup_created_at'), 'topup', ['created_at'], unique=False)
    op.create_table('apikey',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('key_prefix', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('key_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('last_used_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('total_requests', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_cost', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=False),
    sa.Column('abuse_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('allowed_ips', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('allowed_domains', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('apikey_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('apikey_pkey'))
    )
    op.create_index(op.f('ix_apikey_user_id'), 'apikey', ['user_id'], unique=False)
    op.create_index(op.f('ix_apikey_created_at'), 'apikey', ['created_at'], unique=False)
    op.create_table('helpfaq',
    sa.Column('question', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('answer', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('helpfaq_pkey'))
    )
    op.create_table('credit_transfer',
    sa.Column('sender_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('recipient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], name=op.f('credit_transfer_recipient_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], name=op.f('credit_transfer_sender_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('credit_transfer_pkey'))
    )
    op.create_table('campaign',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('recipients', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('progress', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('starts_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('ends_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('total_distributed', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('spent_naira', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('campaign_organization_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('campaign_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('campaign_pkey'))
    )
    op.create_index(op.f('ix_campaign_user_id'), 'campaign', ['user_id'], unique=False)
    op.create_index(op.f('ix_campaign_status'), 'campaign', ['status'], unique=False)
    op.create_index(op.f('ix_campaign_organization_id'), 'campaign', ['organization_id'], unique=False)
    op.create_index(op.f('ix_campaign_name'), 'campaign', ['name'], unique=False)
    op.create_index(op.f('ix_campaign_created_at'), 'campaign', ['created_at'], unique=False)
    op.create_table('ai_chat_messages',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('chat_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tokens_used', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('model', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['ai_chats.id'], name=op.f('ai_chat_messages_chat_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_chat_messages_pkey'))
    )
    op.create_index(op.f('ix_ai_chat_messages_role'), 'ai_chat_messages', ['role'], unique=False)
    op.create_index(op.f('ix_ai_chat_messages_created_at'), 'ai_chat_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_chat_messages_chat_id'), 'ai_chat_messages', ['chat_id'], unique=False)
    op.create_table('workspace_usage_tracking',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('billing_period_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('billing_period_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('total_usage', sa.NUMERIC(precision=12, scale=4), server_default=sa.text('0.0000'), autoincrement=False, nullable=False),
    sa.Column('usage_breakdown', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('workspace_usage_tracking_organization_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('workspace_usage_tracking_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('workspace_usage_tracking_pkey'))
    )
    op.create_index(op.f('ix_workspace_usage_tracking_workspace_id'), 'workspace_usage_tracking', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_workspace_usage_tracking_organization_id'), 'workspace_usage_tracking', ['organization_id'], unique=False)
    op.create_index(op.f('ix_workspace_usage_tracking_billing_period_start'), 'workspace_usage_tracking', ['billing_period_start'], unique=False)
    op.create_index(op.f('ix_workspace_usage_tracking_billing_period_end'), 'workspace_usage_tracking', ['billing_period_end'], unique=False)
    op.create_table('oauth_connection',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('provider_user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('provider_email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('access_token', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('refresh_token', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('token_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('scopes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('last_synced_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('connection_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('oauth_connection_pkey'))
    )
    op.create_index(op.f('ix_oauth_connection_workspace_id'), 'oauth_connection', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_oauth_connection_user_id'), 'oauth_connection', ['user_id'], unique=False)
    op.create_index(op.f('ix_oauth_connection_provider'), 'oauth_connection', ['provider'], unique=False)
    op.create_table('workspace_member_role',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('member_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('assigned_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['workspace_member.id'], name=op.f('workspace_member_role_member_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['workspace_role.id'], name=op.f('workspace_member_role_role_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('workspace_member_role_pkey'))
    )
    op.create_index(op.f('ix_workspace_member_role_role_id'), 'workspace_member_role', ['role_id'], unique=False)
    op.create_index(op.f('ix_workspace_member_role_member_id'), 'workspace_member_role', ['member_id'], unique=False)
    op.create_table('security_event',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('source_ip', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('assigned_to_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['user.id'], name=op.f('security_event_assigned_to_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('security_event_user_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('security_event_pkey'))
    )
    op.create_index(op.f('ix_security_event_type'), 'security_event', ['type'], unique=False)
    op.create_index(op.f('ix_security_event_status'), 'security_event', ['status'], unique=False)
    op.create_index(op.f('ix_security_event_severity'), 'security_event', ['severity'], unique=False)
    op.create_index(op.f('ix_security_event_created_at'), 'security_event', ['created_at'], unique=False)
    op.create_table('helpcategory',
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('icon', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('color', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('bg_color', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('helpcategory_pkey'))
    )
    op.create_table('platform_settings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('general', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('notifications', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('payments', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('gateways', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('email', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('security', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('rate_limiting', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('integrations', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('compliance', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name=op.f('platform_settings_updated_by_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('platform_settings_pkey'))
    )
    op.create_table('organization_model',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('model_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('is_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_default', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['aimodel.id'], name=op.f('organization_model_model_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('organization_model_organization_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('organization_model_pkey'))
    )
    op.create_index(op.f('ix_organization_model_organization_id'), 'organization_model', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_model_model_id'), 'organization_model', ['model_id'], unique=False)
    op.create_table('ai_chats',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('ai_chats_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_chats_pkey'))
    )
    op.create_index(op.f('ix_ai_chats_user_id'), 'ai_chats', ['user_id'], unique=False)
    op.create_index(op.f('ix_ai_chats_created_at'), 'ai_chats', ['created_at'], unique=False)
    op.create_table('project',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('owner_user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), server_default=sa.text("'other'::character varying"), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'in_development'::character varying"), autoincrement=False, nullable=False),
    sa.Column('project_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('org_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('api_key_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['apikey.id'], name=op.f('project_api_key_id_fkey')),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('fk_project_org_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['user.id'], name=op.f('project_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('project_pkey')),
    sa.UniqueConstraint('api_key_id', name=op.f('project_api_key_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_project_type'), 'project', ['type'], unique=False)
    op.create_index(op.f('ix_project_status'), 'project', ['status'], unique=False)
    op.create_index(op.f('ix_project_owner_user_id'), 'project', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_project_name'), 'project', ['name'], unique=False)
    op.create_index(op.f('ix_project_is_deleted'), 'project', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_project_created_at'), 'project', ['created_at'], unique=False)
    op.create_table('workspace_project',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('credits_used', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=False),
    sa.Column('api_calls_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_activity', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('workspace_project_created_by_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('workspace_project_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('workspace_project_pkey'))
    )
    op.create_index(op.f('ix_workspace_project_workspace_id'), 'workspace_project', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_workspace_project_name'), 'workspace_project', ['name'], unique=False)
    op.create_table('wallet',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('owner_type', postgresql.ENUM('organization', 'user', name='walletownertype'), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('wallet_pkey'))
    )
    op.create_index(op.f('ix_wallet_owner_type'), 'wallet', ['owner_type'], unique=False)
    op.create_index(op.f('ix_wallet_owner_id'), 'wallet', ['owner_id'], unique=False)
    op.create_table('notification',
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('metadata_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('notification_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('notification_pkey'))
    )
    op.create_index(op.f('ix_notification_user_id'), 'notification', ['user_id'], unique=False)
    op.create_index(op.f('ix_notification_is_read'), 'notification', ['is_read'], unique=False)
    op.create_index(op.f('ix_notification_created_at'), 'notification', ['created_at'], unique=False)
    op.create_table('workspace_credit_transaction',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=False),
    sa.Column('balance', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('recipient_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('tokens', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['workspace_member.id'], name=op.f('workspace_credit_transaction_recipient_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('workspace_credit_transaction_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('workspace_credit_transaction_pkey'))
    )
    op.create_index(op.f('ix_workspace_credit_transaction_workspace_id'), 'workspace_credit_transaction', ['workspace_id'], unique=False)
    op.create_table('organization',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('credits_balance', sa.NUMERIC(precision=12, scale=4), server_default=sa.text('0.0000'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('organization_owner_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('organization_pkey'))
    )
    op.create_index(op.f('ix_organization_name'), 'organization', ['name'], unique=False)
    op.create_table('workspace',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('avatar', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('credits_balance', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('monthly_credit_limit', sa.NUMERIC(precision=12, scale=4), server_default=sa.text('0.0000'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('workspace_organization_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('workspace_owner_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('workspace_pkey'))
    )
    op.create_index(op.f('ix_workspace_owner_id'), 'workspace', ['owner_id'], unique=False)
    op.create_index(op.f('ix_workspace_organization_id'), 'workspace', ['organization_id'], unique=False)
    op.create_index(op.f('ix_workspace_name'), 'workspace', ['name'], unique=False)
    op.create_table('organization_credit_transaction',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=False),
    sa.Column('balance_after', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('performed_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('organization_credit_transaction_organization_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performed_by'], ['user.id'], name=op.f('organization_credit_transaction_performed_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('organization_credit_transaction_workspace_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('organization_credit_transaction_pkey'))
    )
    op.create_index(op.f('ix_organization_credit_transaction_transaction_type'), 'organization_credit_transaction', ['transaction_type'], unique=False)
    op.create_index(op.f('ix_organization_credit_transaction_organization_id'), 'organization_credit_transaction', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_credit_transaction_created_at'), 'organization_credit_transaction', ['created_at'], unique=False)
    op.create_table('workspace_member',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('credits_allocated', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('joined_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('last_active', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('invited_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('workspace_member_user_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('workspace_member_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('workspace_member_pkey'))
    )
    op.create_index(op.f('ix_workspace_member_workspace_id'), 'workspace_member', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_workspace_member_user_id'), 'workspace_member', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspace_member_invited_email'), 'workspace_member', ['invited_email'], unique=False)
    op.create_table('aiprovider',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('website', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('aiprovider_pkey'))
    )
    op.create_index(op.f('ix_aiprovider_slug'), 'aiprovider', ['slug'], unique=True)
    op.create_index(op.f('ix_aiprovider_name'), 'aiprovider', ['name'], unique=True)
    op.create_table('workspace_role',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_custom', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('permissions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('workspace_role_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('workspace_role_pkey'))
    )
    op.create_index(op.f('ix_workspace_role_workspace_id'), 'workspace_role', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_workspace_role_name'), 'workspace_role', ['name'], unique=False)
    op.create_table('wallet_transaction',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('wallet_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('transaction_type', postgresql.ENUM('top_up', 'credit_share', 'usage', 'refund', 'adjustment', name='wallettransactiontype'), autoincrement=False, nullable=False),
    sa.Column('credit', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=False),
    sa.Column('debit', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=False),
    sa.Column('transfer_in', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=False),
    sa.Column('transfer_out', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('reference_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('idempotency_key', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('wallet_transaction_created_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallet.id'], name=op.f('wallet_transaction_wallet_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('wallet_transaction_pkey'))
    )
    op.create_index(op.f('ix_wallet_transaction_wallet_id'), 'wallet_transaction', ['wallet_id'], unique=False)
    op.create_index(op.f('ix_wallet_transaction_transaction_type'), 'wallet_transaction', ['transaction_type'], unique=False)
    op.create_index(op.f('ix_wallet_transaction_idempotency_key'), 'wallet_transaction', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_wallet_transaction_created_at'), 'wallet_transaction', ['created_at'], unique=False)
    op.create_table('organization_member',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), server_default=sa.text("'member'::character varying"), autoincrement=False, nullable=False),
    sa.Column('joined_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('organization_member_organization_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('organization_member_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('organization_member_pkey'))
    )
    op.create_table('workspace_project_member',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('member_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('added_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['workspace_member.id'], name=op.f('workspace_project_member_member_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['workspace_project.id'], name=op.f('workspace_project_member_project_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('workspace_project_member_pkey'))
    )
    op.create_index(op.f('ix_workspace_project_member_project_id'), 'workspace_project_member', ['project_id'], unique=False)
    op.create_index(op.f('ix_workspace_project_member_member_id'), 'workspace_project_member', ['member_id'], unique=False)
    op.drop_index(op.f('ix_payment_user_id'), table_name='payment')
    op.drop_index(op.f('ix_payment_transaction_reference'), table_name='payment')
    op.drop_index(op.f('ix_payment_created_at'), table_name='payment')
    op.drop_table('payment')
    op.drop_table('event')
    op.drop_index(op.f('ix_announcement_created_at'), table_name='announcement')
    op.drop_table('announcement')
    # ### end Alembic commands ###
