"""add organization_id to role table

Revision ID: add_org_id_to_role
Revises: f96dd5013eb6
Create Date: 2026-01-17 16:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'add_org_id_to_role'
down_revision = 'f96dd5013eb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add organization_id column to role table
    op.add_column('role', sa.Column('organization_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_role_organization_id'), 'role', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'role', 'organization', ['organization_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role', type_='foreignkey')
    op.drop_index(op.f('ix_role_organization_id'), table_name='role')
    op.drop_column('role', 'organization_id')
    # ### end Alembic commands ###
