"""add user status last_login and auth_provider

Revision ID: b066011b6f82
Revises: dcca84879561
Create Date: 2026-01-02 17:21:09.625317

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b066011b6f82'
down_revision = 'dcca84879561'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_connection',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('provider_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provider_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('access_token', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('refresh_token', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('token_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('scopes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('connection_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_connection_provider'), 'oauth_connection', ['provider'], unique=False)
    op.create_index(op.f('ix_oauth_connection_user_id'), 'oauth_connection', ['user_id'], unique=False)
    op.create_index(op.f('ix_oauth_connection_workspace_id'), 'oauth_connection', ['workspace_id'], unique=False)
    # op.create_table('copilot_activity',
    # sa.Column('id', sa.Uuid(), nullable=False),
    # sa.Column('copilot_id', sa.Uuid(), nullable=False),
    # sa.Column('user_id', sa.Uuid(), nullable=False),
    # sa.Column('activity_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    # sa.Column('activity_status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    # sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    # sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    # sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    # sa.Column('activity_metadata', sa.JSON(), nullable=True),
    # sa.Column('unique_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    # sa.Column('created_at', sa.DateTime(), nullable=False),
    # sa.ForeignKeyConstraint(['copilot_id'], ['copilot.id'], ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_copilot_activity_activity_status'), 'copilot_activity', ['activity_status'], unique=False)
    # op.create_index(op.f('ix_copilot_activity_activity_type'), 'copilot_activity', ['activity_type'], unique=False)
    # op.create_index(op.f('ix_copilot_activity_copilot_id'), 'copilot_activity', ['copilot_id'], unique=False)
    # op.create_index(op.f('ix_copilot_activity_created_at'), 'copilot_activity', ['created_at'], unique=False)
    # op.create_index(op.f('ix_copilot_activity_user_id'), 'copilot_activity', ['user_id'], unique=False)
    # op.create_table('copilot_share',
    # sa.Column('id', sa.Uuid(), nullable=False),
    # sa.Column('copilot_id', sa.Uuid(), nullable=False),
    # sa.Column('user_id', sa.Uuid(), nullable=True),
    # sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    # sa.Column('message', sa.Text(), nullable=True),
    # sa.Column('can_edit', sa.Boolean(), nullable=False),
    # sa.Column('can_chat', sa.Boolean(), nullable=False),
    # sa.Column('shared_by', sa.Uuid(), nullable=False),
    # sa.Column('shared_at', sa.DateTime(), nullable=False),
    # sa.ForeignKeyConstraint(['copilot_id'], ['copilot.id'], ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_copilot_share_copilot_id'), 'copilot_share', ['copilot_id'], unique=False)
    # op.create_index(op.f('ix_copilot_share_email'), 'copilot_share', ['email'], unique=False)
    # op.create_index(op.f('ix_copilot_share_shared_at'), 'copilot_share', ['shared_at'], unique=False)
    # op.create_index(op.f('ix_copilot_share_user_id'), 'copilot_share', ['user_id'], unique=False)
    op.create_table('credit_transfer',
    sa.Column('sender_id', sa.Uuid(), nullable=False),
    sa.Column('recipient_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('copilot', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('copilot', 'tags',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('copilot', 'stop_sequences',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('copilot', 'system_prompt',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('copilot', 'suggested_prompts',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('copilot', 'capabilities',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('copilot', 'tools_config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.create_index(op.f('ix_copilot_workspace_id'), 'copilot', ['workspace_id'], unique=False)
    op.drop_constraint(op.f('copilot_workspace_id_fkey'), 'copilot', type_='foreignkey')
    op.drop_constraint(op.f('copilot_created_by_fkey'), 'copilot', type_='foreignkey')
    op.alter_column('copilot_conversation', 'context',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_constraint(op.f('copilot_conversation_user_id_fkey'), 'copilot_conversation', type_='foreignkey')
    op.add_column('copilot_document', sa.Column('document_metadata', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_copilot_document_uploaded_by'), 'copilot_document', ['uploaded_by'], unique=False)
    op.drop_constraint(op.f('copilot_document_uploaded_by_fkey'), 'copilot_document', type_='foreignkey')
    op.drop_column('copilot_document', 'metadata')
    op.add_column('copilot_document_chunk', sa.Column('chunk_metadata', sa.JSON(), nullable=True))
    op.alter_column('copilot_document_chunk', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('ix_copilot_document_chunk_embedding'), table_name='copilot_document_chunk', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_column('copilot_document_chunk', 'metadata')
    op.alter_column('copilot_execution', 'input_message',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_index(op.f('ix_copilot_execution_conversation_id'), 'copilot_execution', ['conversation_id'], unique=False)
    op.drop_constraint(op.f('copilot_execution_user_id_fkey'), 'copilot_execution', type_='foreignkey')
    op.add_column('copilot_message', sa.Column('message_metadata', sa.JSON(), nullable=True))
    op.alter_column('copilot_message', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('copilot_message', 'attachments',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_column('copilot_message', 'metadata')
    op.alter_column('copilot_tool', 'parameters_schema',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('copilot_tool', 'config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('copilot_tool_execution', 'input_params',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('organization', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('organization', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('organization_member', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('permission', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # op.drop_constraint(op.f('permission_name_key'), 'permission', type_='unique')
    op.drop_index(op.f('ix_permission_name'), table_name='permission')
    op.create_index(op.f('ix_permission_name'), 'permission', ['name'], unique=True)
    op.alter_column('project', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_constraint(op.f('fk_project_api_key_id'), 'project', type_='foreignkey')
    op.create_foreign_key(None, 'project', 'apikey', ['api_key_id'], ['id'])
    op.alter_column('role', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # op.drop_constraint(op.f('role_name_key'), 'role', type_='unique')
    op.drop_index(op.f('ix_role_name'), table_name='role')
    op.create_index(op.f('ix_role_name'), 'role', ['name'], unique=True)
    op.alter_column('rolepermission', 'allowed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # Safe addition of user columns
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    user_columns = [c['name'] for c in inspector.get_columns('user')]
    
    if 'username' not in user_columns:
        op.add_column('user', sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True))
        op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    
    if 'phone_number' not in user_columns:
        op.add_column('user', sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
        
    if 'dial_code' not in user_columns:
        op.add_column('user', sa.Column('dial_code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True))
        
    if 'auth_provider' not in user_columns:
        op.add_column('user', sa.Column('auth_provider', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False, server_default='email'))
        
    if 'address' not in user_columns:
        op.add_column('user', sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
        
    if 'postcode' not in user_columns:
        op.add_column('user', sa.Column('postcode', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
        
    if 'city' not in user_columns:
        op.add_column('user', sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
        
    if 'country' not in user_columns:
        op.add_column('user', sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
        
    if 'credits' not in user_columns:
        op.add_column('user', sa.Column('credits', sa.Numeric(precision=12, scale=4), nullable=False, server_default='0.0000'))

    if 'status' not in user_columns:
        op.add_column('user', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False, server_default='active'))
        
    if 'last_login' not in user_columns:
        op.add_column('user', sa.Column('last_login', sa.DateTime(), nullable=True))
        
    op.alter_column('user', 'tag_number',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Unique user tag for identification (e.g., @qor123456)',
               existing_nullable=True)
    op.alter_column('user', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('user', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    # op.add_column('workspace_member', sa.Column('invited_email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # op.create_index(op.f('ix_workspace_member_invited_email'), 'workspace_member', ['invited_email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspace_member_invited_email'), table_name='workspace_member')
    op.drop_column('workspace_member', 'invited_email')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.alter_column('user', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('user', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('user', 'tag_number',
               existing_type=sa.VARCHAR(length=50),
               comment='Unique user tag for identification (e.g., @qor123456)',
               existing_nullable=True)
    op.drop_column('user', 'last_login')
    op.drop_column('user', 'status')
    op.drop_column('user', 'credits')
    op.drop_column('user', 'country')
    op.drop_column('user', 'city')
    op.drop_column('user', 'postcode')
    op.drop_column('user', 'address')
    op.drop_column('user', 'auth_provider')
    op.drop_column('user', 'dial_code')
    op.drop_column('user', 'phone_number')
    op.drop_column('user', 'username')
    op.alter_column('rolepermission', 'allowed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('ix_role_name'), table_name='role')
    op.create_index(op.f('ix_role_name'), 'role', ['name'], unique=False)
    op.create_unique_constraint(op.f('role_name_key'), 'role', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('role', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.create_foreign_key(op.f('fk_project_api_key_id'), 'project', 'apikey', ['api_key_id'], ['id'], ondelete='SET NULL')
    op.alter_column('project', 'deleted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_permission_name'), table_name='permission')
    op.create_index(op.f('ix_permission_name'), 'permission', ['name'], unique=False)
    op.create_unique_constraint(op.f('permission_name_key'), 'permission', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('permission', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('organization_member', 'joined_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('organization', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('organization', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('copilot_tool_execution', 'input_params',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('copilot_tool', 'config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('copilot_tool', 'parameters_schema',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.add_column('copilot_message', sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.alter_column('copilot_message', 'attachments',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('copilot_message', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('copilot_message', 'message_metadata')
    op.create_foreign_key(op.f('copilot_execution_user_id_fkey'), 'copilot_execution', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_copilot_execution_conversation_id'), table_name='copilot_execution')
    op.alter_column('copilot_execution', 'input_message',
               existing_type=sa.TEXT(),
               nullable=False)
    op.add_column('copilot_document_chunk', sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_copilot_document_chunk_embedding'), 'copilot_document_chunk', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.alter_column('copilot_document_chunk', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('copilot_document_chunk', 'chunk_metadata')
    op.add_column('copilot_document', sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('copilot_document_uploaded_by_fkey'), 'copilot_document', 'user', ['uploaded_by'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_copilot_document_uploaded_by'), table_name='copilot_document')
    op.drop_column('copilot_document', 'document_metadata')
    op.create_foreign_key(op.f('copilot_conversation_user_id_fkey'), 'copilot_conversation', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('copilot_conversation', 'context',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.create_foreign_key(op.f('copilot_created_by_fkey'), 'copilot', 'user', ['created_by'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('copilot_workspace_id_fkey'), 'copilot', 'workspace', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_copilot_workspace_id'), table_name='copilot')
    op.alter_column('copilot', 'tools_config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('copilot', 'capabilities',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('copilot', 'suggested_prompts',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('copilot', 'system_prompt',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('copilot', 'stop_sequences',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('copilot', 'tags',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('copilot', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_table('credit_transfer')
    op.drop_index(op.f('ix_copilot_share_user_id'), table_name='copilot_share')
    op.drop_index(op.f('ix_copilot_share_shared_at'), table_name='copilot_share')
    op.drop_index(op.f('ix_copilot_share_email'), table_name='copilot_share')
    op.drop_index(op.f('ix_copilot_share_copilot_id'), table_name='copilot_share')
    op.drop_table('copilot_share')
    op.drop_index(op.f('ix_copilot_activity_user_id'), table_name='copilot_activity')
    op.drop_index(op.f('ix_copilot_activity_created_at'), table_name='copilot_activity')
    op.drop_index(op.f('ix_copilot_activity_copilot_id'), table_name='copilot_activity')
    op.drop_index(op.f('ix_copilot_activity_activity_type'), table_name='copilot_activity')
    op.drop_index(op.f('ix_copilot_activity_activity_status'), table_name='copilot_activity')
    op.drop_table('copilot_activity')
    op.drop_index(op.f('ix_oauth_connection_workspace_id'), table_name='oauth_connection')
    op.drop_index(op.f('ix_oauth_connection_user_id'), table_name='oauth_connection')
    op.drop_index(op.f('ix_oauth_connection_provider'), table_name='oauth_connection')
    op.drop_table('oauth_connection')
    # ### end Alembic commands ###
