"""add analytics fields to campaign

Revision ID: b29c8d64ba51
Revises: 8376ab50ddcb
Create Date: 2026-01-09 08:06:19.707788

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b29c8d64ba51'
down_revision = '8376ab50ddcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign', sa.Column('total_distributed', sa.Numeric(precision=12, scale=2), nullable=False, server_default="0"))
    op.add_column('campaign', sa.Column('spent_naira', sa.Numeric(precision=12, scale=2), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign', 'spent_naira')
    op.drop_column('campaign', 'total_distributed')
    # ### end Alembic commands ###
