"""Add online event fields

Revision ID: dc33e2a31bde
Revises: 14f78c406a21
Create Date: 2026-04-21 11:12:27.085802

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'dc33e2a31bde'
down_revision = '14f78c406a21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('is_online', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('event', sa.Column('meeting_link', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'meeting_link')
    op.drop_column('event', 'is_online')
    # ### end Alembic commands ###
