"""Add description to wallet_transaction

Revision ID: eb295549313b
Revises: 3f33d381c6dc
Create Date: 2026-01-31 17:46:48.998000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'eb295549313b'
down_revision = '3f33d381c6dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet_transaction', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallet_transaction', 'description')
    # ### end Alembic commands ###
