"""add_status_to_org_member

Revision ID: f96dd5013eb6
Revises: 15ace1d067b7
Create Date: 2026-01-17 11:15:16.661881

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f96dd5013eb6'
down_revision = '15ace1d067b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('copilot_activity',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('copilot_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('activity_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('activity_status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('activity_metadata', sa.JSON(), nullable=True),
    sa.Column('unique_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['copilot_id'], ['copilot.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_copilot_activity_activity_status'), 'copilot_activity', ['activity_status'], unique=False)
    op.create_index(op.f('ix_copilot_activity_activity_type'), 'copilot_activity', ['activity_type'], unique=False)
    op.create_index(op.f('ix_copilot_activity_copilot_id'), 'copilot_activity', ['copilot_id'], unique=False)
    op.create_index(op.f('ix_copilot_activity_created_at'), 'copilot_activity', ['created_at'], unique=False)
    op.create_index(op.f('ix_copilot_activity_user_id'), 'copilot_activity', ['user_id'], unique=False)
    op.create_table('copilot_share',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('copilot_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('can_edit', sa.Boolean(), nullable=False),
    sa.Column('can_chat', sa.Boolean(), nullable=False),
    sa.Column('shared_by', sa.Uuid(), nullable=False),
    sa.Column('shared_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['copilot_id'], ['copilot.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_copilot_share_copilot_id'), 'copilot_share', ['copilot_id'], unique=False)
    op.create_index(op.f('ix_copilot_share_email'), 'copilot_share', ['email'], unique=False)
    op.create_index(op.f('ix_copilot_share_shared_at'), 'copilot_share', ['shared_at'], unique=False)
    op.create_index(op.f('ix_copilot_share_user_id'), 'copilot_share', ['user_id'], unique=False)
    # Ensure abuse_score exists on apikey
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    
    # 1. APIKey abuse_score safety
    columns = [c['name'] for c in inspector.get_columns('apikey')]
    if 'abuse_score' not in columns:
        op.add_column('apikey', sa.Column('abuse_score', sa.Integer(), nullable=False, server_default=sa.text('0')))
    else:
        op.alter_column('apikey', 'abuse_score',
                   existing_type=sa.INTEGER(),
                   nullable=False,
                   existing_server_default=sa.text('0'))

    # 2. Credit Transfer safety
    op.alter_column('credit_transfer', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('credit_transfer', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
               
    # Safe index drops for credit_transfer
    ct_indexes = [i['name'] for i in inspector.get_indexes('credit_transfer')]
    for idx in ['ix_credit_transfer_created_at', 'ix_credit_transfer_recipient_id', 'ix_credit_transfer_sender_id', 'ix_credit_transfer_status']:
        if idx in ct_indexes:
            op.drop_index(idx, table_name='credit_transfer')
            
    # Safe constraint drops for credit_transfer
    ct_fks = [f['name'] for f in inspector.get_foreign_keys('credit_transfer')]
    for fk in ['credit_transfer_sender_id_fkey', 'credit_transfer_recipient_id_fkey']:
        if fk in ct_fks:
            op.drop_constraint(fk, 'credit_transfer', type_='foreignkey')
            
    op.create_foreign_key(None, 'credit_transfer', 'user', ['sender_id'], ['id'])
    op.create_foreign_key(None, 'credit_transfer', 'user', ['recipient_id'], ['id'])

    # 3. OAuth Connection safety
    op.alter_column('oauth_connection', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('oauth_connection', 'scopes',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('oauth_connection', 'last_synced_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('oauth_connection', 'connection_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('oauth_connection', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('oauth_connection', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
               
    oc_indexes = [i['name'] for i in inspector.get_indexes('oauth_connection')]
    if 'ix_oauth_connection_user_provider' in oc_indexes:
        op.drop_index('ix_oauth_connection_user_provider', table_name='oauth_connection')

    # 4. Organization Member safety
    om_columns = [c['name'] for c in inspector.get_columns('organization_member')]
    if 'status' not in om_columns:
        op.add_column('organization_member', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
        op.execute("UPDATE organization_member SET status = 'active'")
        op.alter_column('organization_member', 'status', nullable=False)
        
    op.alter_column('organization_member', 'joined_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organization_member', 'joined_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('organization_member', 'status')
    op.create_index(op.f('ix_oauth_connection_user_provider'), 'oauth_connection', ['user_id', 'provider'], unique=False)
    op.alter_column('oauth_connection', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('oauth_connection', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('oauth_connection', 'connection_metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('oauth_connection', 'last_synced_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('oauth_connection', 'scopes',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('oauth_connection', 'expires_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_constraint(None, 'credit_transfer', type_='foreignkey')
    op.drop_constraint(None, 'credit_transfer', type_='foreignkey')
    op.create_foreign_key(op.f('credit_transfer_recipient_id_fkey'), 'credit_transfer', 'user', ['recipient_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('credit_transfer_sender_id_fkey'), 'credit_transfer', 'user', ['sender_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_credit_transfer_status'), 'credit_transfer', ['status'], unique=False)
    op.create_index(op.f('ix_credit_transfer_sender_id'), 'credit_transfer', ['sender_id'], unique=False)
    op.create_index(op.f('ix_credit_transfer_recipient_id'), 'credit_transfer', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_credit_transfer_created_at'), 'credit_transfer', ['created_at'], unique=False)
    op.alter_column('credit_transfer', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('credit_transfer', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('apikey', 'abuse_score',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_copilot_share_user_id'), table_name='copilot_share')
    op.drop_index(op.f('ix_copilot_share_shared_at'), table_name='copilot_share')
    op.drop_index(op.f('ix_copilot_share_email'), table_name='copilot_share')
    op.drop_index(op.f('ix_copilot_share_copilot_id'), table_name='copilot_share')
    op.drop_table('copilot_share')
    op.drop_index(op.f('ix_copilot_activity_user_id'), table_name='copilot_activity')
    op.drop_index(op.f('ix_copilot_activity_created_at'), table_name='copilot_activity')
    op.drop_index(op.f('ix_copilot_activity_copilot_id'), table_name='copilot_activity')
    op.drop_index(op.f('ix_copilot_activity_activity_type'), table_name='copilot_activity')
    op.drop_index(op.f('ix_copilot_activity_activity_status'), table_name='copilot_activity')
    op.drop_table('copilot_activity')
    # ### end Alembic commands ###
