"""add wallet and ledger tables

Revision ID: ff950ce044f6
Revises: 32e6102dd038
Create Date: 2026-01-28 23:49:25.810363

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ff950ce044f6'
down_revision = '32e6102dd038'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    if 'wallet' not in tables:
        op.create_table('wallet',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('owner_type', sa.Enum('organization', 'user', name='walletownertype'), nullable=False),
        sa.Column('owner_id', sa.Uuid(), nullable=False),
        sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_wallet_owner_id'), 'wallet', ['owner_id'], unique=False)
        op.create_index(op.f('ix_wallet_owner_type'), 'wallet', ['owner_type'], unique=False)

    if 'wallet_transaction' not in tables:
        op.create_table('wallet_transaction',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('wallet_id', sa.Uuid(), nullable=False),
        sa.Column('transaction_type', sa.Enum('top_up', 'credit_share', 'usage', 'refund', 'adjustment', name='wallettransactiontype'), nullable=False),
        sa.Column('credit', sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column('debit', sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column('transfer_in', sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column('transfer_out', sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column('amount', sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column('reference_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column('created_by', sa.Uuid(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['wallet_id'], ['wallet.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_wallet_transaction_created_at'), 'wallet_transaction', ['created_at'], unique=False)
        op.create_index(op.f('ix_wallet_transaction_idempotency_key'), 'wallet_transaction', ['idempotency_key'], unique=True)
        op.create_index(op.f('ix_wallet_transaction_transaction_type'), 'wallet_transaction', ['transaction_type'], unique=False)
        op.create_index(op.f('ix_wallet_transaction_wallet_id'), 'wallet_transaction', ['wallet_id'], unique=False)
    
    # Check if columns already exist before adding
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    
    # Check copilot_message.agent_steps
    copilot_cols = [c['name'] for c in inspector.get_columns('copilot_message')]
    if 'agent_steps' not in copilot_cols:
        op.add_column('copilot_message', sa.Column('agent_steps', sa.JSON(), nullable=True))
        
    # Check workspace_credit_transaction.tokens
    ws_cols = [c['name'] for c in inspector.get_columns('workspace_credit_transaction')]
    if 'tokens' not in ws_cols:
        op.add_column('workspace_credit_transaction', sa.Column('tokens', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if columns exist before dropping
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    
    # Check workspace_credit_transaction.tokens
    ws_cols = [c['name'] for c in inspector.get_columns('workspace_credit_transaction')]
    if 'tokens' in ws_cols:
        op.drop_column('workspace_credit_transaction', 'tokens')
        
    # Check copilot_message.agent_steps
    copilot_cols = [c['name'] for c in inspector.get_columns('copilot_message')]
    if 'agent_steps' in copilot_cols:
        op.drop_column('copilot_message', 'agent_steps')
        
    op.drop_index(op.f('ix_wallet_transaction_wallet_id'), table_name='wallet_transaction')
    op.drop_index(op.f('ix_wallet_transaction_transaction_type'), table_name='wallet_transaction')
    op.drop_index(op.f('ix_wallet_transaction_idempotency_key'), table_name='wallet_transaction')
    op.drop_index(op.f('ix_wallet_transaction_created_at'), table_name='wallet_transaction')
    op.drop_table('wallet_transaction')
    op.drop_index(op.f('ix_wallet_owner_type'), table_name='wallet')
    op.drop_index(op.f('ix_wallet_owner_id'), table_name='wallet')
    op.drop_table('wallet')
    # ### end Alembic commands ###
