# Copilot Hub Schemas
from app.copilot.schemas.copilot import (
    CopilotCreate,
    CopilotUpdate,
    CopilotPublic,
    CopilotsPublic,
    CopilotSettings,
    CopilotFilters,
    ShareCopilotRequest,
    CopilotSuggestionsResponse,
    CopilotWorkspaceAssignment,
)
from app.copilot.schemas.conversation import (
    ConversationCreate,
    ConversationUpdate,
    ConversationPublic,
    ConversationsPublic,
    MessageCreate,
    MessageUpdate,
    MessagePublic,
    MessagesPublic,
    SendMessageRequest,
    SendMessageResponse,
    MessageFeedback,
    StreamChunk,
)
from app.copilot.schemas.document import (
    DocumentCreate,
    DocumentUpdate,
    DocumentPublic,
    DocumentsPublic,
    DocumentChunkPublic,
    DocumentSearchRequest,
    DocumentSearchResult,
    DocumentSearchResponse,
    DocumentUploadResponse,
    DocumentProcessingStatus,
)
from app.copilot.schemas.tool import (
    ToolCreate,
    ToolUpdate,
    ToolPublic,
    ToolsPublic,
    ToolExecutionCreate,
    ToolExecutionPublic,
    ToolExecutionsPublic,
    RAGSearchParams,
    HTTPRequestParams,
    HTTPRequestResult,
    DatabaseQueryParams,
    DatabaseQueryResult,
    EmailSendParams,
    EmailSendResult,
    FileRetrievalParams,
    FileRetrievalResult,
    WebSearchParams,
    WebSearchResult,
    CodeExecutionParams,
    CodeExecutionResult,
)

__all__ = [
    # Copilot
    "CopilotCreate",
    "CopilotUpdate",
    "CopilotPublic",
    "CopilotsPublic",
    "CopilotSettings",
    "CopilotFilters",
    "ShareCopilotRequest",
    "CopilotSuggestionsResponse",
    "CopilotWorkspaceAssignment",
    # Conversation
    "ConversationCreate",
    "ConversationUpdate",
    "ConversationPublic",
    "ConversationsPublic",
    "MessageCreate",
    "MessageUpdate",
    "MessagePublic",
    "MessagesPublic",
    "SendMessageRequest",
    "SendMessageResponse",
    "MessageFeedback",
    "StreamChunk",
    # Document
    "DocumentCreate",
    "DocumentUpdate",
    "DocumentPublic",
    "DocumentsPublic",
    "DocumentChunkPublic",
    "DocumentSearchRequest",
    "DocumentSearchResult",
    "DocumentSearchResponse",
    "DocumentUploadResponse",
    "DocumentProcessingStatus",
    # Tool
    "ToolCreate",
    "ToolUpdate",
    "ToolPublic",
    "ToolsPublic",
    "ToolExecutionCreate",
    "ToolExecutionPublic",
    "ToolExecutionsPublic",
    "RAGSearchParams",
    "HTTPRequestParams",
    "HTTPRequestResult",
    "DatabaseQueryParams",
    "DatabaseQueryResult",
    "EmailSendParams",
    "EmailSendResult",
    "FileRetrievalParams",
    "FileRetrievalResult",
    "WebSearchParams",
    "WebSearchResult",
    "CodeExecutionParams",
    "CodeExecutionResult",
]
